apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  heroes-web-deploy
  labels:
    name:  heroes-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  heroes-web
    spec:
      containers:
      - image: <login server>/azureworkshop/rating-web:v1
        name:  heroes-web-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  API
          value:  http://heroes-api:3000/api     
        - name:  SITE
          value:  http://heroes-web:8080/static/data/site.json
        - name:  HEROES
          value:  http://heroes-web:8080/static/data/heroes.json
        ports:
        - containerPort:  8080
          name:  heroes-web
      restartPolicy: Always
      imagePullPolicy: Always