apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  heroes-web
  labels:
    name:  heroes-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  heroes-web
    spec:
      containers:
      - image: <login server>/rating-web:v1
        name:  heroes-web-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  API
          value:  http://40.121.194.253:3000/api     
        - name:  SITE
          value:  http://40.71.39.235:8080/static/data/justice/heroes-site.json
        - name:  HEROES
          value:  http://40.71.39.235:8080/static/data/justice/heroes.json
        ports:
        - containerPort:  8080
          name:  heroes-web
        imagePullPolicy: Always
      restartPolicy: Always