apiVersion: v1
kind: Service
metadata:
  name: heroes-web
  labels:
    name: heroes-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: heroes-web